#!/bin/bash
set -eu -o pipefail

/usr/bin/apt-get update -qq
/usr/bin/apt-get dist-upgrade -qq --show-upgraded --dry-run \
  | wc -l \
  | while read n; do
      case $n in
        0) exit 0;;
	*) exit 51;;
      esac
    done
